// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class ActividadFisica
{
    public int Id { get; set; }

    public int Usuario { get; set; }

    public int TipoActividadFisica { get; set; }

    public int Duracion { get; set; }

    public decimal? Distancia { get; set; }

    public int Calorias { get; set; }

    public string Comentarios { get; set; }

    public bool? Eliminado { get; set; }

    public virtual TipoActividadFisica TipoActividadFisicaNavigation { get; set; }

    public virtual Usuario UsuarioNavigation { get; set; }
}