// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class AlimentoConsumido
{
    public int Id { get; set; }

    public int Dieta { get; set; }

    public int Alimento { get; set; }

    public int Opcion { get; set; }

    public virtual Alimento AlimentoNavigation { get; set; }

    public virtual Dieta DietaNavigation { get; set; }
}