// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class AlimentoConsumido
{
    public int Id { get; set; }

    public int TipoComida { get; set; }

    public int Dieta { get; set; }

    public string Descripcion { get; set; }

    public bool? Eliminado { get; set; }

    public virtual Dieta DietaNavigation { get; set; }

    public virtual TipoComida TipoComidaNavigation { get; set; }
}