// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class Alimento
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public int Calorias { get; set; }

    public bool? Eliminado { get; set; }

    public virtual ICollection<AlimentoConsumido> AlimentoConsumido { get; set; } = new List<AlimentoConsumido>();
}