// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class BitacoraPeso
{
    public int Id { get; set; }

    public int Usuario { get; set; }

    public decimal Peso { get; set; }

    public DateTime Fecha { get; set; }

    public virtual Usuario UsuarioNavigation { get; set; }
}