// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class Dieta
{
    public int Id { get; set; }

    public int Revision { get; set; }

    public int TipoComida { get; set; }

    public string Comentarios { get; set; }

    public bool? Eliminado { get; set; }

    public virtual ICollection<AlimentoConsumido> AlimentoConsumidos { get; set; } = new List<AlimentoConsumido>();

    public virtual Revision RevisionNavigation { get; set; }

    public virtual TipoComida TipoComidaNavigation { get; set; }
}