// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class Medicion
{
    public int Id { get; set; }

    public int TipoMedida { get; set; }

    public decimal? ValorMedicion { get; set; }

    public bool? Eliminado { get; set; }

    public virtual TipoMedida TipoMedidaNavigation { get; set; }
}