// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class MetaSalud
{
    public int Id { get; set; }

    public int Revision { get; set; }

    public int TipoMeta { get; set; }

    public decimal PesoObjectivo { get; set; }

    public DateTime FechaObjectivo { get; set; }

    public string NivelActividad { get; set; }

    public string OjectivoEspecifico { get; set; }

    public bool? Eliminado { get; set; }

    public virtual Revision RevisionNavigation { get; set; }

    public virtual TipoMeta TipoMetaNavigation { get; set; }
}