// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class MetaSalud
{
    public int Id { get; set; }

    public int Usuario { get; set; }

    public int TipoMeta { get; set; }

    public int PesoObjectivo { get; set; }

    public int FechaObjectivo { get; set; }

    public string NivelActividad { get; set; }

    public string OjectivoEspecifico { get; set; }

    public virtual TipoMeta TipoMetaNavigation { get; set; }

    public virtual Usuario UsuarioNavigation { get; set; }
}