// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class TipoComida
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Dieta> Dieta { get; set; } = new List<Dieta>();
}