// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class TipoMeta
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<MetaSalud> MetaSalud { get; set; } = new List<MetaSalud>();
}