// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class TipoMedida
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public bool? Eliminado { get; set; }
}