// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string NombreUsuario { get; set; }

    public string Correo { get; set; }

    public string Contrasena { get; set; }

    public string Nombre { get; set; }

    public DateTime FechaNacimiento { get; set; }

    public int Altura { get; set; }

    public int TipoAltura { get; set; }

    public decimal Peso { get; set; }

    public int Genero { get; set; }

    public string Foto { get; set; }

    public bool? Eliminado { get; set; }

    public virtual Genero GeneroNavigation { get; set; }

    public virtual ICollection<Revision> Revisions { get; set; } = new List<Revision>();

    public virtual TipoAltura TipoAlturaNavigation { get; set; }
}