// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fitness.Model.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string NombreUsuario { get; set; }

    public string Correo { get; set; }

    public string Contrasena { get; set; }

    public string Nombre { get; set; }

    public DateTime FechaNacimiento { get; set; }

    public int Altura { get; set; }

    public int TipoAltura { get; set; }

    public int Peso { get; set; }

    public int TipoPeso { get; set; }

    public int Genero { get; set; }

    public string Foto { get; set; }

    public virtual ICollection<ActividadFisica> ActividadFisicas { get; set; } = new List<ActividadFisica>();

    public virtual ICollection<Dieta> Dieta { get; set; } = new List<Dieta>();

    public virtual Genero GeneroNavigation { get; set; }

    public virtual ICollection<MetaSalud> MetaSalud { get; set; } = new List<MetaSalud>();

    public virtual TipoAltura TipoAlturaNavigation { get; set; }

    public virtual TipoPeso TipoPesoNavigation { get; set; }
}