// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Fitness.Model.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Fitness.Data;

public partial class FTContext : DbContext
{
    public FTContext(DbContextOptions<FTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActividadFisica> ActividadFisicas { get; set; }

    public virtual DbSet<AlimentoConsumido> AlimentoConsumidos { get; set; }

    public virtual DbSet<Dieta> Dieta { get; set; }

    public virtual DbSet<Genero> Generos { get; set; }

    public virtual DbSet<Medicion> Medicions { get; set; }

    public virtual DbSet<MetaSalud> MetaSaluds { get; set; }

    public virtual DbSet<Revision> Revisions { get; set; }

    public virtual DbSet<TipoActividadFisica> TipoActividadFisicas { get; set; }

    public virtual DbSet<TipoAltura> TipoAlturas { get; set; }

    public virtual DbSet<TipoComida> TipoComida { get; set; }

    public virtual DbSet<TipoDistancia> TipoDistancia { get; set; }

    public virtual DbSet<TipoMedida> TipoMedida { get; set; }

    public virtual DbSet<TipoMeta> TipoMeta { get; set; }

    public virtual DbSet<TipoPeso> TipoPesos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<ActividadFisica>(entity =>
        {
            entity.ToTable("ActividadFisica");

            entity.Property(e => e.Comentarios)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Distancia).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Eliminado).HasDefaultValue(false);

            entity.HasOne(d => d.RevisionNavigation).WithMany(p => p.ActividadFisicas)
                .HasForeignKey(d => d.Revision)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ActividadFisica_Revision");

            entity.HasOne(d => d.TipoNavigation).WithMany(p => p.ActividadFisicas)
                .HasForeignKey(d => d.Tipo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ActividadFisica_TipoActivadadFisica");

            entity.HasOne(d => d.TipoDistanciaNavigation).WithMany(p => p.ActividadFisicas)
                .HasForeignKey(d => d.TipoDistancia)
                .HasConstraintName("FK_ActividadFisica_TipoDistancia");
        });

        modelBuilder.Entity<AlimentoConsumido>(entity =>
        {
            entity.ToTable("AlimentoConsumido");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);

            entity.HasOne(d => d.DietaNavigation).WithMany(p => p.AlimentoConsumidos)
                .HasForeignKey(d => d.Dieta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AlimentoConsumido_Dieta");

            entity.HasOne(d => d.TipoComidaNavigation).WithMany(p => p.AlimentoConsumidos)
                .HasForeignKey(d => d.TipoComida)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AlimentoConsumido_TipoComida");
        });

        modelBuilder.Entity<Dieta>(entity =>
        {
            entity.Property(e => e.Comentarios)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);

            entity.HasOne(d => d.RevisionNavigation).WithMany(p => p.Dieta)
                .HasForeignKey(d => d.Revision)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Dieta_Revision");

            entity.HasOne(d => d.TipoComidaNavigation).WithMany(p => p.Dieta)
                .HasForeignKey(d => d.TipoComida)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Dieta_Usuario");
        });

        modelBuilder.Entity<Genero>(entity =>
        {
            entity.ToTable("Genero");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<Medicion>(entity =>
        {
            entity.ToTable("Medicion");

            entity.Property(e => e.Eliminado).HasDefaultValue(false);
            entity.Property(e => e.ValorMedicion).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.TipoMedidaNavigation).WithMany(p => p.Medicions)
                .HasForeignKey(d => d.TipoMedida)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Medicion_TipoMedida");
        });

        modelBuilder.Entity<MetaSalud>(entity =>
        {
            entity.ToTable("MetaSalud");

            entity.Property(e => e.Eliminado).HasDefaultValue(false);
            entity.Property(e => e.FechaObjectivo).HasColumnType("datetime");
            entity.Property(e => e.NivelActividad)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.OjectivoEspecifico)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.PesoObjectivo).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.RevisionNavigation).WithMany(p => p.MetaSaluds)
                .HasForeignKey(d => d.Revision)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MetaSalud_Revision");

            entity.HasOne(d => d.TipoMetaNavigation).WithMany(p => p.MetaSaluds)
                .HasForeignKey(d => d.TipoMeta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MetaSalud_TipoMeta");
        });

        modelBuilder.Entity<Revision>(entity =>
        {
            entity.ToTable("Revision");

            entity.Property(e => e.Eliminado).HasDefaultValue(false);
            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.HasOne(d => d.UsuarioNavigation).WithMany(p => p.Revisions)
                .HasForeignKey(d => d.Usuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Revision_Usuario");
        });

        modelBuilder.Entity<TipoActividadFisica>(entity =>
        {
            entity.ToTable("TipoActividadFisica");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<TipoAltura>(entity =>
        {
            entity.ToTable("TipoAltura");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<TipoComida>(entity =>
        {
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<TipoDistancia>(entity =>
        {
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<TipoMedida>(entity =>
        {
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<TipoMeta>(entity =>
        {
            entity.Property(e => e.Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<TipoPeso>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Peso");

            entity.ToTable("TipoPeso");

            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.ToTable("Usuario");

            entity.Property(e => e.Contrasena)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Correo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Eliminado).HasDefaultValue(false);
            entity.Property(e => e.FechaNacimiento).HasColumnType("datetime");
            entity.Property(e => e.Foto)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Peso).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.GeneroNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.Genero)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Genero");

            entity.HasOne(d => d.TipoAlturaNavigation).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.TipoAltura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_TipoAltura");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}